kind: pipeline
name: test
platform:
  os: linux
  arch: amd64

volumes:
  - name: shiro
    host:
      path: /tmp/shiro
  - name: shiro-dist
    host:
      path: /tmp/shiro-dist
  - name: shiro-env
    host:
      path: /home/innei/docker-compose/drone/public/shiro/.env

steps:
  - name: install
    image: node:20-alpine
    commands:
      - 'pwd'
      # - 'wget http://10.0.0.33:18888/shiro/.env'
      - 'npm i -g pnpm'
      - 'pnpm install --no-frozen-lockfil'
    volumes:
      - name: shiro-env
        path: /drone/src/.env

  - name: build
    image: node:20-alpine
    commands:
      - 'npm run build'
    volumes:
      - name: shiro-env
        path: /drone/src/.env

    depends_on:
      - install

  - name: package
    image: node:20-alpine
    commands:
      - 'apk add zip'
      - 'mkdir -p temp'
      - 'rm -rf .next/cache'
      - 'cp .next/standalone/* temp/ -r'
      - 'rm -rf .next/standalone'
      - 'cp .next/* temp/ -r'
      - 'cp public temp/ -r'
      - 'mkdir assets'
      - 'zip -r ./assets/dist.zip ./tmp -P tmp'

    volumes:
      - name: shiro
        path: /drone/src/assets
      - name: shiro-dist
        path: /drone/src/.next

    depends_on:
      - build
# trigger:
#   event:
#     include:
#       - push
# node:
#   node: runner-slave-A
# trigger:
#   event:
#     include:
#       - tag
