kind: pipeline
name: test
platform:
  os: linux
  arch: amd64
steps:
  - name: install
    image: node:20-alpine
    commands:

        - 'npm i -g pnpm'
        - 'pnpm install --no-frozen-lockfil'

  - name: build
    image: node:20-alpine
    commands:
        - 'wget http://10.0.0.33:18888/shiro/.env'
        - 'npm run build'
    depends_on:
      - install
# trigger:
#   event:
#     include:
#       - push
# node:
#   node: runner-slave-A
# trigger:
#   event:
#     include:
#       - tag
