kind: pipeline
name: test
platform:
  os: linux
  arch: amd64
steps:
  - name: install
    image: node:20-alpine
    commands:
        - 'wget http://drone-http:8080/.env'
        - 'cat .env'
  #     - 'npm i -g pnpm'
  #     - 'pnpm install --no-frozen-lockfil'

  # - name: build
  #   image: node:20-alpine
  #   commands:
  #     - 'npm i -g @vercel/cli'
  #     - 'npm run build'
  #   depends_on:
  #     - install
# trigger:
#   event:
#     include:
#       - push
# node:
#   node: runner-slave-A
# trigger:
#   event:
#     include:
#       - tag
