kind: pipeline
name: test
platform:
  os: linux
  arch: amd64

volumes:
  - name: shiro
    host:
      path: /tmp/shiro
  - name: shiro-dist
    host:
      path: /tmp/shiro-dist
  - name: shiro-env
    host:
      path: /home/innei/docker-compose/drone/public/shiro/.env
  - name: dns
    host:
      path: /etc/resolv.conf

steps:
  - name: install
    image: node:20-alpine
    commands:
      - 'pwd'
      # - 'wget http://10.0.0.33:18888/shiro/.env'
      - 'npm i -g pnpm'
      - 'pnpm install --no-frozen-lockfil'
    volumes:
      - name: shiro-env
        path: /drone/src/.env
      - name: dns
        path: /etc/resolv.conf

  - name: build
    image: node:20-alpine
    commands:
      - 'nslookup fonts.gstatic.com'
      - 'npm run build'
    volumes:
      - name: shiro-env
        path: /drone/src/.env
      - name: dns
        path: /etc/resolv.conf
      # - name: shiro-dist
      #   path: /drone/src/.next

    depends_on:
      - install

  - name: package
    image: node:20-alpine
    commands:
      - 'pwd'
      - 'ls -a'
      - 'ls .next'
      - 'apk add zip'
      - 'sh ./standalone-bundle.sh'

      # - 'mkdir -p temp'
      # - 'rm -rf .next/cache'
      # - 'cp .next/standalone/* temp/ -r'
      # - 'rm -rf .next/standalone'
      # - 'cp .next/* temp/ -r'
      # - 'cp public temp/ -r'
      # - 'mkdir -p assets'
      # - 'cd temp'
      # - 'zip -r ../assets/dist.zip ./'

    # volumes:
    #   - name: shiro
    #     path: /drone/src/assets
    #   - name: shiro-dist
    #     path: /drone/src/temp

    depends_on:
      - build

  - name: deploy
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      port: 22
      target: /home/deploy/shiro.zip
      source:
        - assets/release.zip
      rm_target: true
      strip_components: 1
      debug: true
    depends_on:
      - package
# trigger:
#   event:
#     include:
#       - push
# node:
#   node: runner-slave-A
# trigger:
#   event:
#     include:
#       - tag
