kind: pipeline
name: test
platform:
  os: linux
  arch: amd64

volumes:
  - name: shiro
    host:
      path: /tmp/shiro

steps:
  - name: install
    image: node:20-alpine
    commands:
      - 'pwd'
      - 'wget http://10.0.0.33:18888/shiro/.env'
      - 'npm i -g pnpm'
      - 'pnpm install --no-frozen-lockfil'

  - name: build
    image: node:20-alpine
    commands:
      - 'npm run build'
      - 'apk add zip'
      - 'mkdir -p temp'
      - 'rm -rf .next/cache'
      - 'cp .next/standalone/* temp/ -r'
      - 'rm -rf .next/standalone'
      - 'cp .next/* temp/.next -r'
      - 'cp public temp/ -r'
      - 'cd temp'
      - 'zip -r ../dist.zip .'
    volumes:
      - name: shiro
        path: /app
    depends_on:
      - install
# trigger:
#   event:
#     include:
#       - push
# node:
#   node: runner-slave-A
# trigger:
#   event:
#     include:
#       - tag
